---
- name: Start jitsi docker container
  become_user: "{{ jitsi_service_user }}"
  shell: |
    cd "{{ config_folder }}"
    docker-compose up -d

- name: Fix file permissions on host
  become: yes
  become_user: root
  shell: |
    chmod 777 "{{ config_folder }}"
