---
- hosts: localhost
  gather_facts: false
  become: no
  tasks:
    - name: "Check ansible version >=2.7.8"
      assert:
        msg: "Ansible must be v2.7.8 or higher"
        that:
          - ansible_version.string is version("2.7.8", ">=")
  vars:
    ansible_connection: local

- hosts: jitsi-host[0]
  roles:
    - { role: ./roles/manage/stop }
    - { role: ./roles/configure_docker/remove }
    - { role: ./roles/configure_host/remove }
